apiVersion: v1
kind: ConfigMap
metadata:
  name: ott-microservice-config
  namespace: c8
  labels:
    app: ott-microservice
data:
  GDN_URL: GDN_URL
  API_KEY: API_KEY
  TMDB_API_KEY: TMDB_API_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott-microservice
  namespace: c8
  labels:
    app: ott-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ott-microservice
  template:
    metadata:
      labels:
        app: ott-microservice
    spec:
      affinity: {}
      containers:
        - name: ott-microservice
          image: tusharspawar/ott-microservice:latest
          imagePullPolicy: Always
          securityContext: {}
          env:
            - name: GDN_URL
              valueFrom:
                configMapKeyRef:
                  name: ott-microservice-config
                  key: GDN_URL
            - name: API_KEY
              valueFrom:
                configMapKeyRef:
                  name: ott-microservice-config
                  key: API_KEY
            - name: TMDB_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: ott-microservice-config
                  key: TMDB_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ott-microservice
  namespace: c8
  labels:
    app: ott-microservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4000
      protocol: TCP
  selector:
    app: ott-microservice
---
# C8DB coordinator Ambassador mapping CR
#
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: ott-microservice-mapping
  namespace: c8
  labels:
    app: ott-microservice
spec:
  prefix: /ott/api/
  service: ott-microservice:4000
